### ISSUE TITLE
the difference of joints coordinates of successive frames is big

### ISSUE THREAD

**Issue by cissoidx** [hongluzhou/composer#3]
Hello @hongluzhou ,

When running the collective activity dataset, I found that the difference of joints coordinates of successive frames is big.

> (Pdb) len(joint_dxcoords)
19293300
(Pdb) np.histogram(joint_dxcoords)
(array([    4455,     5897,     9256,     8636,  1998641, 17242240,
           7888,     7894,     5020,     3373]), array([-7.99904283e+02, -6.40013798e+02, -4.80123314e+02, -3.20232829e+02,
       -1.60342345e+02, -4.51860162e-01,  1.59438624e+02,  3.19329109e+02,
        4.79219593e+02,  6.39110078e+02,  7.99000562e+02]))

We can see that tens of thousands of elements in joint_dxcoords are more than 100, although the proportion of these big elements is small. Does this violate the assumptions of TOKS? Will this affect the training of the model?

cheers,
xu

**Comment by hongluzhou** [comment]
The small proportion of those big elements may come from noisy estimated keypoints, which may further due to noisy input bounding box, etc. In our work, TOKS is only used as one type of input keypoint features and it measures the temporal difference between two keypoints. The model learns to utilize this feature. In our initial experiments on the Volleyball dataset, we found this feature can improve the model's group activity recognition performance.
